spring:
  application:
    name: ${API_GATEWAY_NAME}
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI}
          jwk-set-uri: ${SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_JWK_SET_URI}

server:
  port: ${API_GATEWAY_PORT}

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER_URL}
    register-with-eureka: true
    fetch-registry: true
    enabled: true
    healthcheck:
      enabled: true
  instance:
    hostname: ${API_GATEWAY_INSTANCE_HOSTNAME}
    instance-id: "${spring.application.name}:${server.port}"
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
  tracing:
    enabled: true
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: ${MANAGEMENT_TRACING_ZIPKIN_ENDPOINT}
  metrics:
    distribution:
      percentiles-histogram:
        http:
          server:
            requests: true

logging:
  level:
    root: INFO
    com.netflix.eureka: DEBUG
    com.netflix.discovery: DEBUG
    org.springframework.cloud.gateway: TRACE
    org.springframework.cloud.gateway.route.RouteDefinitionLocator: INFO
    io.micrometer.tracing: DEBUG
    org.springframework.security: DEBUG
    brave: DEBUG
    reactor.netty.http.client: DEBUG
  pattern:
    level: "%5p [${spring.application.name:}, %X{traceId:-}, %X{spanId:-}]"

# Optional Gateway routing (uncomment if needed)
# spring:
#   cloud:
#     gateway:
#       discovery:
#         locator:
#           enabled: true
#           lower-case-service-id: true
#       routes:
#         - id: discovery-server
#           uri: http://discovery-server:8761
#           predicates:
#             - Path=/eureka/web/**
#           filters:
#             - SetPath=/
#         - id: discovery-server-static
#           uri: http://discovery-server:8761
#           predicates:
#             - Path=/eureka
#         - id: order-service
#           uri: lb://order-service
#           predicates:
#             - Path=/api/order/**
#         - id: product-service
#           uri: lb://product-service
#           predicates:
#             - Path=/api/product/**
#         - id: inventory-service
#           uri: lb://inventory-service
#           predicates:
#             - Path=/api/inventory/**
