# =========================================================
# APPLICATION
# =========================================================
spring.application.name=${API_GATEWAY_NAME:api-gateway}
server.port=${API_GATEWAY_PORT:8080}

# =========================================================
# SECURITY / JWT / KEYCLOAK
# =========================================================
spring.security.oauth2.resourceserver.jwt.issuer-uri=${SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI}
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=${SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_JWK_SET_URI}

# =========================================================
# EUREKA CLIENT
# =========================================================
eureka.client.enabled=true
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.client.healthcheck.enabled=true

eureka.client.service-url.defaultZone=${EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE}

eureka.instance.hostname=${API_GATEWAY_INSTANCE_HOSTNAME}
eureka.instance.instance-id=${spring.application.name}:${server.port}
eureka.instance.prefer-ip-address=true

# =========================================================
# ACTUATOR / OBSERVABILITY
# =========================================================
management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always

# =========================================================
# TRACING / ZIPKIN
# =========================================================
management.tracing.enabled=true
management.tracing.sampling.probability=1.0

management.zipkin.tracing.endpoint=${MANAGEMENT_TRACING_ZIPKIN_ENDPOINT}

management.metrics.distribution.percentiles-histogram.http.server.requests=true

spring.cloud.gateway.observability.enabled=true

# =========================================================
# LOGGING
# =========================================================
logging.level.root=INFO

logging.level.com.netflix.eureka=INFO
logging.level.com.netflix.discovery=INFO

logging.level.org.springframework.security=INFO

logging.level.org.springframework.cloud.gateway=INFO
logging.level.org.springframework.cloud.gateway.route.RouteDefinitionLocator=INFO

logging.level.io.micrometer.tracing=INFO
logging.level.brave=INFO

logging.pattern.level=%5p [${spring.application.name}, %X{traceId:-}, %X{spanId:-}]

# =========================================================
# SPRING CLOUD GATEWAY
# =========================================================
#spring.cloud.gateway.discovery.locator.enabled=true
#spring.cloud.gateway.discovery.locator.lower-case-service-id=true

# =========================================================
# SWAGGER / OPENAPI
# =========================================================
springdoc.api-docs.enabled=true

springdoc.swagger-ui.enabled=true
springdoc.swagger-ui.path=/swagger-ui.html

springdoc.swagger-ui.urls[0].name=order-service
springdoc.swagger-ui.urls[0].url=/order-service/v3/api-docs

springdoc.swagger-ui.urls[1].name=product-service
springdoc.swagger-ui.urls[1].url=/product-service/v3/api-docs

springdoc.swagger-ui.urls[2].name=inventory-service
springdoc.swagger-ui.urls[2].url=/inventory-service/v3/api-docs

springdoc.swagger-ui.urls[3].name=user-service
springdoc.swagger-ui.urls[3].url=/user-service/v3/api-docs

springdoc.swagger-ui.urls[4].name=auth-service
springdoc.swagger-ui.urls[4].url=/auth-service/v3/api-docs

# =========================================================
# ROUTES
# =========================================================

# =============================
# Eureka Dashboard
# =============================
spring.cloud.gateway.routes[0].id=discovery-server-web
spring.cloud.gateway.routes[0].uri=http://discovery-server:8761
spring.cloud.gateway.routes[0].predicates[0]=Path=/eureka/web/**
spring.cloud.gateway.routes[0].filters[0]=SetPath=/

# =============================
# Eureka Static Resources
# =============================
spring.cloud.gateway.routes[1].id=discovery-server-static
spring.cloud.gateway.routes[1].uri=http://discovery-server:8761
spring.cloud.gateway.routes[1].predicates[0]=Path=/eureka/**

# =============================
# ORDER SERVICE
# =============================
spring.cloud.gateway.routes[2].id=order-service
spring.cloud.gateway.routes[2].uri=lb://ORDER-SERVICE
spring.cloud.gateway.routes[2].predicates[0]=Path=/api/orders/**

# =============================
# PRODUCT SERVICE
# =============================
spring.cloud.gateway.routes[3].id=product-service
spring.cloud.gateway.routes[3].uri=lb://PRODUCT-SERVICE
spring.cloud.gateway.routes[3].predicates[0]=Path=/api/products/**

# =============================
# INVENTORY SERVICE
# =============================
spring.cloud.gateway.routes[4].id=inventory-service
spring.cloud.gateway.routes[4].uri=lb://INVENTORY-SERVICE
spring.cloud.gateway.routes[4].predicates[0]=Path=/api/inventory/**

# =============================
# USER SERVICE
# =============================
spring.cloud.gateway.routes[5].id=user-service
spring.cloud.gateway.routes[5].uri=lb://USER-SERVICE
spring.cloud.gateway.routes[5].predicates[0]=Path=/api/users/**

# =============================
# AUTH SERVICE
# =============================
spring.cloud.gateway.routes[6].id=auth-service
spring.cloud.gateway.routes[6].uri=lb://AUTH-SERVICE
spring.cloud.gateway.routes[6].predicates[0]=Path=/api/auth/**

# =========================================================
# SWAGGER ROUTES
# =========================================================

spring.cloud.gateway.routes[7].id=order-service-docs
spring.cloud.gateway.routes[7].uri=lb://ORDER-SERVICE
spring.cloud.gateway.routes[7].predicates[0]=Path=/order-service/v3/api-docs
spring.cloud.gateway.routes[7].filters[0]=RewritePath=/order-service/(?<path>.*), /${path}

spring.cloud.gateway.routes[8].id=product-service-docs
spring.cloud.gateway.routes[8].uri=lb://PRODUCT-SERVICE
spring.cloud.gateway.routes[8].predicates[0]=Path=/product-service/v3/api-docs
spring.cloud.gateway.routes[8].filters[0]=RewritePath=/product-service/(?<path>.*), /${path}

spring.cloud.gateway.routes[9].id=inventory-service-docs
spring.cloud.gateway.routes[9].uri=lb://INVENTORY-SERVICE
spring.cloud.gateway.routes[9].predicates[0]=Path=/inventory-service/v3/api-docs
spring.cloud.gateway.routes[9].filters[0]=RewritePath=/inventory-service/(?<path>.*), /${path}

spring.cloud.gateway.routes[10].id=user-service-docs
spring.cloud.gateway.routes[10].uri=lb://USER-SERVICE
spring.cloud.gateway.routes[10].predicates[0]=Path=/user-service/v3/api-docs
spring.cloud.gateway.routes[10].filters[0]=RewritePath=/user-service/(?<path>.*), /${path}

spring.cloud.gateway.routes[11].id=auth-service-docs
spring.cloud.gateway.routes[11].uri=lb://AUTH-SERVICE
spring.cloud.gateway.routes[11].predicates[0]=Path=/auth-service/v3/api-docs
spring.cloud.gateway.routes[11].filters[0]=RewritePath=/auth-service/(?<path>.*), /${path}