message: Config Server

server:
  port: ${CONFIG_SERVER_PORT:8888}

spring:
  application:
    name: ${CONFIG_SERVER_NAME:config-server}

eureka:
  client:
    enabled: true
    register-with-eureka: true
    fetch-registry: true

    healthcheck:
      enabled: true

    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE}

  instance:
    hostname: ${spring.application.name}
    instance-id: ${spring.application.name}:${server.port}
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: "*"

  endpoint:
    health:
      show-details: always
      probes:
        enabled: true

  health:
    livenessstate:
      enabled: true

    readinessstate:
      enabled: true

  tracing:
    enabled: true

    sampling:
      probability: 1.0

  zipkin:
    tracing:
      endpoint: ${MANAGEMENT_TRACING_ZIPKIN_ENDPOINT}

  metrics:
    distribution:
      percentiles-histogram:
        http:
          server:
            requests: true

logging:
  pattern:
    level: "%5p [${spring.application.name}, %X{traceId:-}, %X{spanId:-}]"

springdoc:
  api-docs:
    path: /v3/api-docs

  swagger-ui:
    enabled: true
    path: /swagger-ui.html