server:
  port: ${AUTH_SERVICE_PORT:8086}

spring:
  application:
    name: ${AUTH_SERVICE_NAME:auth-service}

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE:http://eureka:eureka@discovery-server:8761/eureka/}