# ====   APPLICATION CONFIGURATION   ===
spring:
  application:
    name: ${EUREKA_SERVER_NAME}

server:
  port: ${EUREKA_SERVER_PORT}

# ===   SPRING SECURITY CONFIGURATION   ===
eureka:
  username: ${EUREKA_USERNAME}
  password: ${EUREKA_PASSWORD}

  # ===    EUREKA SERVER CONFIGURATION   ===
  instance:
    hostname: ${EUREKA_SERVER_INSTANCE_HOSTNAME}
    instance-id: ${spring.application.name}:${server.port}
    prefer-ip-address: true

  client:
    register-with-eureka: false
    fetch-registry: false
    enabled: true
    healthcheck:
      enabled: true

# ===   TRACING & METRICS CONFIGURATION   ===
management:
  tracing:
    enabled: true
    sampling:
      probability: 1.0
    zipkin:
      tracing:
        endpoint: ${MANAGEMENT_TRACING_ZIPKIN_ENDPOINT}
  metrics:
    distribution:
      percentiles-histogram:
        http:
          server:
            requests: true
  endpoints:
    web:
      exposure:
        include: "*"
    health:
      show-details: always

# ===   LOGGING CONFIGURATION    ===
logging:
  pattern:
    level: "%5p [${spring.application.name:}, %X{traceId:-}, %X{spanId:-}]"
