# ===   SERVER CONFIGURATION   ===
spring:
  application:
    name: ${INVENTORY_SERVICE_NAME}

  datasource:
    driver-class-name: ${SPRING_DATASOURCE_DRIVER_CLASS_NAME_MYSQL}
    url: ${SPRING_DATASOURCE_URL_MYSQL}
    username: ${SPRING_DATASOURCE_USERNAME_MYSQL}
    password: ${SPRING_DATASOURCE_PASSWORD_MYSQL}

  jpa:
    hibernate:
      ddl-auto: ${SPRING_JPA_HIBERNATE_DDL_AUTO_MYSQL}

server:
  port: ${INVENTORY_SERVICE_PORT}

# ===   EUREKA CLIENT CONFIGURATION   ===
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER_URL}
    register-with-eureka: true
    fetch-registry: true
    enabled: true
    healthcheck:
      enabled: true
  instance:
    hostname: ${INVENTORY_SERVICE_INSTANCE_HOSTNAME}
    instance-id: ${spring.application.name}:${server.port}
    prefer-ip-address: true

# ===   TRACING / ZIPKIN   ===
management:
  tracing:
    enabled: true
    sampling:
      probability: 1.0
    zipkin:
      tracing:
        endpoint: ${MANAGEMENT_TRACING_ZIPKIN_ENDPOINT}
  metrics:
    distribution:
      percentiles-histogram:
        http:
          server:
            requests: true
  endpoints:
    web:
      exposure:
        include: "*"
    health:
      show-details: always

# ===   LOGGING  ===
logging:
  pattern:
    level: "%5p [${spring.application.name:}, %X{traceId:-}, %X{spanId:-}]"
