spring:
  application:
    name: ${NOTIFICATION_SERVICE_NAME:notification-service}

  kafka:
    bootstrap-servers: kafka:29092

    template:
      default-topic: order-events

    consumer:
      group-id: notificationId
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer

      properties:
        spring:
          json:
            type:
              mapping: event:com.arseniolourenco.notification_service.OrderPlacedEvent
            trusted:
              packages: "*"
            fail-on-unknown-properties: false

server:
  port: ${NOTIFICATION_SERVICE_PORT:8080}

# eureka:
#   client:
#     service-url:
#       defaultZone: ${EUREKA_SERVER_URL}
#     register-with-eureka: true
#     fetch-registry: true
#     enabled: true
#     healthcheck:
#       enabled: true
#   instance:
#     hostname: ${NOTIFICATION_SERVICE_INSTANCE_HOSTNAME}
#     instance-id: ${spring.application.name}:${server.port}
#     prefer-ip-address: true

# management:
#   tracing:
#     enabled: true
#     sampling:
#       probability: 1.0
#
#   zipkin:
#     tracing:
#       endpoint: ${MANAGEMENT_TRACING_ZIPKIN_ENDPOINT}
#
#   metrics:
#     distribution:
#       percentiles-histogram:
#         http:
#           server:
#             requests: true
#
#   endpoints:
#     web:
#       exposure:
#         include: "*"
#
#   endpoint:
#     health:
#       show-details: always

logging:
  level:
    root: INFO
    com.netflix.eureka: DEBUG
    com.netflix.discovery: DEBUG
    org.springframework.cloud.gateway: TRACE
    org.springframework.cloud.gateway.route.RouteDefinitionLocator: INFO

# logging:
#   pattern:
#     level: "%5p [${spring.application.name:}, %X{traceId:-}, %X{spanId:-}]"