spring:
  application:
    name: notification-service

  kafka:
    bootstrap-servers: kafka:29092

    template:
      default-topic: order-events

    consumer:
      group-id: notificationId
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring:
          json:
            value:
              default:
                type: com.arseniolourenco.notification_service.OrderPlacedEvent
            use:
              type:
                headers: false
            trusted:
              packages: "*"
            fail-on-unknown-properties: false

server:
  port: 8080

logging:
  level:
    root: INFO
    com.netflix.eureka: DEBUG
    com.netflix.discovery: DEBUG
    org.springframework.cloud.gateway: TRACE
    org.springframework.cloud.gateway.route.RouteDefinitionLocator: INFO
