spring:
  application:
    name: product-service

  data:
    mongodb:
      host: mongo
      port: 27017
      username: ${MONGO_INITDB_ROOT_USERNAME:mongoadmin}
      password: ${MONGO_INITDB_ROOT_PASSWORD:secret}
      database: ${MONGO_INITDB_DATABASE:productDB}
      authentication-database: admin
    redis:
      host: redis
      port: 6379


server:
  port: 8080
