spring:
  application:
    name: product-service

  data:
    mongodb:
      host: mongo
      port: 27017
      username: mongoadmin
      password: secret
      database: productDB
      authentication-database: admin

server:
  port: 8080
